// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzmus7MSI_AOXAYKz3-fSTojv_CLMuH8M',
    appId: '1:760257501482:web:37f64715bf0010cf9ca653',
    messagingSenderId: '760257501482',
    projectId: 'lotus-connect-41bcf',
    authDomain: 'lotus-connect-41bcf.firebaseapp.com',
    storageBucket: 'lotus-connect-41bcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzmus7MSI_AOXAYKz3-fSTojv_CLMuH8M',
    appId: '1:760257501482:android:37f64715bf0010cf9ca653',
    messagingSenderId: '760257501482',
    projectId: 'lotus-connect-41bcf',
    storageBucket: 'lotus-connect-41bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzmus7MSI_AOXAYKz3-fSTojv_CLMuH8M',
    appId: '1:760257501482:ios:37f64715bf0010cf9ca653',
    messagingSenderId: '760257501482',
    projectId: 'lotus-connect-41bcf',
    iosBundleId: 'devblock.tech.lotus_connect',
    storageBucket: 'lotus-connect-41bcf.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzmus7MSI_AOXAYKz3-fSTojv_CLMuH8M',
    appId: '1:760257501482:ios:37f64715bf0010cf9ca653',
    messagingSenderId: '760257501482',
    projectId: 'lotus-connect-41bcf',
    iosBundleId: 'devblock.tech.lotus_connect',
    storageBucket: 'lotus-connect-41bcf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzmus7MSI_AOXAYKz3-fSTojv_CLMuH8M',
    appId: '1:760257501482:web:37f64715bf0010cf9ca653',
    messagingSenderId: '760257501482',
    projectId: 'lotus-connect-41bcf',
    authDomain: 'lotus-connect-41bcf.firebaseapp.com',
    storageBucket: 'lotus-connect-41bcf.firebasestorage.app',
  );
}
